spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json